steps:
  # Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:latest'
      - '.'
    timeout: 1800s

  # Push de la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:latest'

  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rumbia-cotizador'
      - '--image'
      - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:$COMMIT_SHA'
  - 'gcr.io/is-geniaton-ifs-2025-g3/rumbia-cotizador:latest'

timeout: 2400s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

